/* -*- Mode: C; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/*
 *  Copyright (C) 2012 Theppitak Karoonboonyanan <theppitak@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#include "thaikb.h"

#include <thai/tis.h>

#define N_KEYCODES  54

static const unsigned char tis_keycode_map[3][N_KEYCODES] =
{
  { /* level 1 */
    /* 0x00 */
    0x00, 0x00, TIS_YMBOL_BAHT, '/',
    '-', TIS_PHO_SAMPHAO, TIS_THO_THUNG, TIS_SARA_U,
    TIS_SARA_UE, TIS_KHO_KHWAI, TIS_TO_TAO, TIS_CHO_CHAN,
    TIS_KHO_KHAI, TIS_CHO_CHANG, 0x08, 0x09,
    /* 0x10 */
    TIS_MAIYAMOK, TIS_SARA_AI_MAIMALAI, TIS_SARA_AM, TIS_PHO_PHAN,
    TIS_SARA_A, TIS_MAI_HAN_AKAT, TIS_SARA_II, TIS_RO_RUA,
    TIS_NO_NU, TIS_YO_YAK, TIS_BO_BAIMAI, TIS_LO_LING,
    0x0d, 0x00, TIS_FO_FAN, TIS_HO_HIP,
    /* 0x20 */
    TIS_KO_KAI, TIS_DO_DEK, TIS_SARA_E, TIS_MAI_THO,
    TIS_MAI_EK, TIS_SARA_AA, TIS_SO_SUA, TIS_WO_WAEN,
    TIS_NGO_NGU, TIS_FONGMAN, 0x00, TIS_KHO_KHON,
    TIS_PHO_PHUNG, TIS_PO_PLA, TIS_SARA_AE, TIS_O_ANG,
    /* 0x30 */
    TIS_SARA_I, TIS_SARA_UEE, TIS_THO_THAHAN, TIS_MO_MA,
    TIS_SARA_AI_MAIMUAN, TIS_FO_FA,
  },
  { /* level 2 */
    /* 0x00 */
    0x00, 0x00, TIS_LAKKHANGYAO, TIS_THAI_DIGIT_ONE,
    TIS_THAI_DIGIT_TWO, TIS_THAI_DIGIT_THREE, TIS_THAI_DIGIT_FOUR, TIS_SARA_UU,
    TIS_YAMAKKAN, TIS_THAI_DIGIT_FIVE, TIS_THAI_DIGIT_SIX, TIS_THAI_DIGIT_SEVEN,
    TIS_THAI_DIGIT_EIGHT, TIS_THAI_DIGIT_NINE, 0x08, 0x09,
    /* 0x10 */
    TIS_THAI_DIGIT_ZERO, '"', TIS_DO_CHADA, TIS_THO_NANGMONTHO,
    TIS_THO_THONG, TIS_NIKHAHIT, TIS_MAI_TRI, TIS_NO_NEN,
    TIS_PAIYANNOI, TIS_YO_YING, TIS_THO_THAN, ',',
    0x0d, 0x00, TIS_RU, TIS_KHO_RAKHANG,
    /* 0x20 */
    TIS_TO_PATAK, TIS_SARA_O, TIS_CHO_CHOE, TIS_MAITAIKHU,
    TIS_MAI_CHATTAWA, TIS_SO_RUSI, TIS_SO_SALA, TIS_SO_SO,
    '.', TIS_KHOMUT, 0x00, TIS_KHO_KHUAT,
    '(', ')', TIS_CHO_CHING, TIS_HO_NOKHUK,
    /* 0x30 */
    TIS_PHINTHU, TIS_THANTHAKHAT, '?', TIS_THO_PHUTHAO,
    TIS_LO_CHULA, TIS_LU,
  },
  { /* level 3 */
    /* 0x00 */
    0x00, 0x00, TIS_LAKKHANGYAO, TIS_THAI_DIGIT_ONE,
    TIS_THAI_DIGIT_TWO, TIS_THAI_DIGIT_THREE, TIS_THAI_DIGIT_FOUR, TIS_SARA_UU,
    TIS_YAMAKKAN, TIS_THAI_DIGIT_FIVE, TIS_THAI_DIGIT_SIX, TIS_THAI_DIGIT_SEVEN,
    TIS_THAI_DIGIT_EIGHT, TIS_THAI_DIGIT_NINE, 0x08, 0x09,
    /* 0x10 */
    TIS_THAI_DIGIT_ZERO, '"', TIS_DO_CHADA, TIS_THO_NANGMONTHO,
    TIS_THO_THONG, TIS_NIKHAHIT, TIS_MAI_TRI, TIS_NO_NEN,
    TIS_ANGKHANKHU, TIS_YO_YING, TIS_THO_THAN, ',',
    0x0d, 0x00, TIS_RU, TIS_KHO_RAKHANG,
    /* 0x20 */
    TIS_TO_PATAK, TIS_SARA_O, TIS_CHO_CHOE, TIS_MAITAIKHU,
    TIS_MAI_CHATTAWA, TIS_SO_RUSI, TIS_SO_SALA, TIS_SO_SO,
    '.', TIS_KHOMUT, 0x00, TIS_KHO_KHUAT,
    '(', ')', TIS_CHO_CHING, TIS_HO_NOKHUK,
    /* 0x30 */
    TIS_PHINTHU, TIS_THANTHAKHAT, '?', TIS_THO_PHUTHAO,
    TIS_LO_CHULA, TIS_LU,
  },
};

static const unsigned char ketmanee_keycode_map[3][N_KEYCODES] =
{
  { /* level 1 */
    /* 0x00 */
    0x00, 0x00, TIS_LAKKHANGYAO, '/',
    '-', TIS_PHO_SAMPHAO, TIS_THO_THUNG, TIS_SARA_U,
    TIS_SARA_UE, TIS_KHO_KHWAI, TIS_TO_TAO, TIS_CHO_CHAN,
    TIS_KHO_KHAI, TIS_CHO_CHANG, 0x08, 0x09,
    /* 0x10 */
    TIS_MAIYAMOK, TIS_SARA_AI_MAIMALAI, TIS_SARA_AM, TIS_PHO_PHAN,
    TIS_SARA_A, TIS_MAI_HAN_AKAT, TIS_SARA_II, TIS_RO_RUA,
    TIS_NO_NU, TIS_YO_YAK, TIS_BO_BAIMAI, TIS_LO_LING,
    0x0d, 0x00, TIS_FO_FAN, TIS_HO_HIP,
    /* 0x20 */
    TIS_KO_KAI, TIS_DO_DEK, TIS_SARA_E, TIS_MAI_THO,
    TIS_MAI_EK, TIS_SARA_AA, TIS_SO_SUA, TIS_WO_WAEN,
    TIS_NGO_NGU, '_', 0x00, TIS_KHO_KHUAT,
    TIS_PHO_PHUNG, TIS_PO_PLA, TIS_SARA_AE, TIS_O_ANG,
    /* 0x30 */
    TIS_SARA_I, TIS_SARA_UEE, TIS_THO_THAHAN, TIS_MO_MA,
    TIS_SARA_AI_MAIMUAN, TIS_FO_FA,
  },
  { /* level 2 */
    0x00, 0x00, '+', TIS_THAI_DIGIT_ONE,
    TIS_THAI_DIGIT_TWO, TIS_THAI_DIGIT_THREE, TIS_THAI_DIGIT_FOUR, TIS_SARA_UU,
    TIS_YMBOL_BAHT, TIS_THAI_DIGIT_FIVE, TIS_THAI_DIGIT_SIX, TIS_THAI_DIGIT_SEVEN,
    TIS_THAI_DIGIT_EIGHT, TIS_THAI_DIGIT_NINE, 0x08, 0x09,
    /* 0x10 */
    TIS_THAI_DIGIT_ZERO, '"', TIS_DO_CHADA, TIS_THO_NANGMONTHO,
    TIS_THO_THONG, TIS_NIKHAHIT, TIS_MAI_TRI, TIS_NO_NEN,
    TIS_PAIYANNOI, TIS_YO_YING, TIS_THO_THAN, ',',
    0x0d, 0x00, TIS_RU, TIS_KHO_RAKHANG,
    /* 0x20 */
    TIS_TO_PATAK, TIS_SARA_O, TIS_CHO_CHOE, TIS_MAITAIKHU,
    TIS_MAI_CHATTAWA, TIS_SO_RUSI, TIS_SO_SALA, TIS_SO_SO,
    '.', '%', 0x00, TIS_KHO_KHON,
    '(', ')', TIS_CHO_CHING, TIS_HO_NOKHUK,
    TIS_PHINTHU, TIS_THANTHAKHAT, '?', TIS_THO_PHUTHAO,
    TIS_LO_CHULA, TIS_LU,
  },
  { /* level 3 */
    /* 0x00 */
    0x00, 0x00, '+', TIS_THAI_DIGIT_ONE,
    TIS_THAI_DIGIT_TWO, TIS_THAI_DIGIT_THREE, TIS_THAI_DIGIT_FOUR, TIS_SARA_UU,
    TIS_YMBOL_BAHT, TIS_THAI_DIGIT_FIVE, TIS_THAI_DIGIT_SIX, TIS_THAI_DIGIT_SEVEN,
    TIS_THAI_DIGIT_EIGHT, TIS_THAI_DIGIT_NINE, 0x08, 0x09,
    /* 0x10 */
    TIS_THAI_DIGIT_ZERO, '"', TIS_DO_CHADA, TIS_THO_NANGMONTHO,
    TIS_THO_THONG, TIS_NIKHAHIT, TIS_MAI_TRI, TIS_NO_NEN,
    TIS_PAIYANNOI, TIS_YO_YING, TIS_THO_THAN, ',',
    0x0d, 0x00, TIS_RU, TIS_KHO_RAKHANG,
    /* 0x20 */
    TIS_TO_PATAK, TIS_SARA_O, TIS_CHO_CHOE, TIS_MAITAIKHU,
    TIS_MAI_CHATTAWA, TIS_SO_RUSI, TIS_SO_SALA, TIS_SO_SO,
    '.', '%', 0x00, TIS_KHO_KHON,
    '(', ')', TIS_CHO_CHING, TIS_HO_NOKHUK,
    /* 0x30 */
    TIS_PHINTHU, TIS_THANTHAKHAT, '?', TIS_THO_PHUTHAO,
    TIS_LO_CHULA, TIS_LU,
  },
};

static const unsigned char pattachote_keycode_map[3][N_KEYCODES] =
{
  { /* level 1 */
    /* 0x00 */
    0x00, 0x00, '=', TIS_THAI_DIGIT_TWO,
    TIS_THAI_DIGIT_THREE, TIS_THAI_DIGIT_FOUR, TIS_THAI_DIGIT_FIVE, TIS_SARA_UU,
    TIS_THAI_DIGIT_SEVEN, TIS_THAI_DIGIT_EIGHT, TIS_THAI_DIGIT_NINE, TIS_THAI_DIGIT_ZERO,
    TIS_THAI_DIGIT_ONE, TIS_THAI_DIGIT_SIX, 0x08, 0x09,
    /* 0x10 */
    TIS_MAITAIKHU, TIS_TO_TAO, TIS_YO_YAK, TIS_O_ANG,
    TIS_RO_RUA, TIS_MAI_EK, TIS_DO_DEK, TIS_MO_MA,
    TIS_WO_WAEN, TIS_SARA_AE, TIS_SARA_AI_MAIMUAN, TIS_CHO_CHOE,
    0x0d, 0x00, TIS_MAI_THO, TIS_THO_THAHAN,
    /* 0x20 */
    TIS_NGO_NGU, TIS_KO_KAI, TIS_MAI_HAN_AKAT, TIS_SARA_II,
    TIS_SARA_AA, TIS_NO_NU, TIS_SARA_E, TIS_SARA_AI_MAIMALAI,
    TIS_KHO_KHAI, '_', 0x00, TIS_LAKKHANGYAO,
    TIS_BO_BAIMAI, TIS_PO_PLA, TIS_LO_LING, TIS_HO_HIP,
    /* 0x30 */
    TIS_SARA_I, TIS_KHO_KHWAI, TIS_SO_SUA, TIS_SARA_A,
    TIS_CHO_CHAN, TIS_PHO_PHAN,
  },
  { /* level 2 */
    /* 0x00 */
    0x00, 0x00, '+', '"',
    '/', ',', '?', TIS_SARA_U,
    '_', '.', '(', ')',
    '-', '%', 0x08, 0x09,
    /* 0x10 */
    TIS_MAI_TRI, TIS_RU, TIS_MAIYAMOK, TIS_YO_YING,
    TIS_SO_RUSI, TIS_SARA_UE, TIS_FO_FA, TIS_SO_SO,
    TIS_THO_THUNG, TIS_THO_PHUTHAO, TIS_PAIYANNOI, ',',
    0x0d, 0x00, TIS_MAI_CHATTAWA, TIS_THO_THONG,
    /* 0x20 */
    TIS_SARA_AM, TIS_NO_NEN, TIS_THANTHAKHAT, TIS_SARA_UEE,
    TIS_PHO_PHUNG, TIS_CHO_CHANG, TIS_SARA_O, TIS_KHO_RAKHANG,
    TIS_THO_NANGMONTHO, TIS_YMBOL_BAHT, 0x00, TIS_NIKHAHIT,
    TIS_DO_CHADA, TIS_TO_PATAK, TIS_THO_THAN, TIS_PHO_SAMPHAO,
    /* 0x30 */
    TIS_PHINTHU, TIS_SO_SALA, TIS_HO_NOKHUK, TIS_FO_FAN,
    TIS_CHO_CHING, TIS_LO_CHULA,
  },
  { /* level 3 */
    /* 0x00 */
    0x00, 0x00, '+', '"',
    '/', ',', '?', TIS_SARA_U,
    '_', '.', '(', ')',
    '-', '%', 0x08, 0x09,
    /* 0x10 */
    TIS_MAI_TRI, TIS_RU, TIS_MAIYAMOK, TIS_YO_YING,
    TIS_SO_RUSI, TIS_SARA_UE, TIS_FO_FA, TIS_SO_SO,
    TIS_THO_THUNG, TIS_THO_PHUTHAO, TIS_PAIYANNOI, ',',
    0x0d, 0x00, TIS_MAI_CHATTAWA, TIS_THO_THONG,
    /* 0x20 */
    TIS_SARA_AM, TIS_NO_NEN, TIS_THANTHAKHAT, TIS_SARA_UEE,
    TIS_PHO_PHUNG, TIS_CHO_CHANG, TIS_SARA_O, TIS_KHO_RAKHANG,
    TIS_THO_NANGMONTHO, TIS_YMBOL_BAHT, 0x00, TIS_NIKHAHIT,
    TIS_DO_CHADA, TIS_TO_PATAK, TIS_THO_THAN, TIS_PHO_SAMPHAO,
    /* 0x30 */
    TIS_PHINTHU, TIS_SO_SALA, TIS_HO_NOKHUK, TIS_FO_FAN,
    TIS_CHO_CHING, TIS_LO_CHULA,
  },
};

static const unsigned char (* const thai_keycode_map[])[N_KEYCODES] =
{
  ketmanee_keycode_map,
  pattachote_keycode_map,
  tis_keycode_map
};

unsigned char
thai_map_keycode (ThaiKBMap map, int keycode, int shift_lv)
{
  if (map > THAI_KB_TIS820_2538 || shift_lv >= 3 || keycode >= N_KEYCODES)
    return 0;

  return thai_keycode_map[map][shift_lv][keycode];
}

/*
vi:ts=2:ai:expandtab
*/
